# Generated by Django 4.0.4 on 2022-04-12 01:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets_api', '0004_alter_ticket_date_alter_ticket_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='image',
        ),
    ]
