# Generated by Django 4.0.4 on 2022-04-12 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets_api', '0006_remove_ticket_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='event_date',
            field=models.DateField(null=True),
        ),
    ]
