# Generated by Django 4.0.4 on 2022-04-12 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets_api', '0007_ticket_event_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='img',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
