# Generated by Django 4.0.4 on 2022-04-15 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets_api', '0008_ticket_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='event_date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
