# Generated by Django 4.0.4 on 2022-04-15 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets_api', '0009_alter_ticket_event_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='img',
        ),
        migrations.AlterField(
            model_name='ticket',
            name='event_date',
            field=models.DateField(null=True),
        ),
    ]
